version: '3'
services:
    zk-03:
        image: zookeeper:3.5.5
        restart: always
        container_name: zk-03
        ports:
            - 2182:2181 # client port
            - 2889:2888 # follower port
            - 3889:3888 # election port
        environment:
            #quorumListenOnAllIPs: true
            ZOO_MY_ID: 3
            ZOO_SERVERS: ${ZOO_SERVERS}
        network_mode: "host"
