version: '3'
services:
    zk-02:
        image: zookeeper:3.5.5
        restart: always
        container_name: zk-02
        ports:
            - 2181:2181 # client port
            - 2888:2888 # follower port
            - 3888:3888 # election port
        environment:
            #quorumListenOnAllIPs: true
            ZOO_MY_ID: 2
            ZOO_SERVERS: ${ZOO_SERVERS}
        network_mode: "host"
